[platformio]
default_envs = esp32-s3-touch-lcd-1-46

[env:esp32-s3-touch-lcd-1-46]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32s3box
framework = arduino
upload_speed = 921600
monitor_speed = 115200

build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14
build_flags = 
	-std=gnu++17
	-I include
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_HAS_PSRAM
	-D CORE_DEBUG_LEVEL=1
	-D A0=0
	-D LV_CONF_INCLUDE_SIMPLE
    ; SensESP Config
    -D SENSESP_ENABLE_WIFI
    -D SENSESP_WIFI_CONFIG_FILE='"/wifi.json"'

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

lib_deps = 
	signalk/SensESP @ ^3.0.0
	lvgl/lvgl @ ^8.3.11
	esp-arduino-libs/esp-lib-utils
	https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1
	https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
